Multiple Changes
- Cleaned up lockfile
- Added err_msg and log_msg to liberrorwraps

diff --git a/main/ham b/main/ham
--- a/main/ham
+++ b/main/ham
@@ -35,18 +35,31 @@ exec >> $LOG_FILE
 
 # ---------- Check for PID File ----------
 if [[ -f $PID_FILE ]]; then
-	cat $PID_FILE | xargs kill
+	PID=$(cat $PID_FILE)
+	kill $PID
+	if [[ $? != 0 ]]; then
+		logger "ham: failed to kill $PID"
+		rm $PID_FILE
+		exit 1
+	fi
 fi
 
+COUNT=0
 while [[ -f $PID_FILE ]]; do
 	sleep 0.5
+	((COUNT++))
+	if ((COUNT > 10)); then
+		rm $PID_FILE
+		logger "ham: $PID_FILE still exists. Timing out after $COUNT iterations."
+		exit 1
+	fi
 done
 
 # ---------- Run Initial Hamster Command ----------
 hamster "$@"
 
 if [[ $? -ne 0 ]]; then
-	printf "\"Hamster $@\" failed\n\n"
+	logger "ham: hamster command failed"
 	exit 1
 else
 	print_panel
@@ -59,7 +72,6 @@ fi
 
 
 if [[ $action == "start" ]]; then
-	trap "exit" INT TERM
 	trap "rm $PID_FILE && kill 0" EXIT
 	activity=$2
 	while true; do
