Update scripts

diff --git a/main/pim b/main/pim
--- a/main/pim
+++ b/main/pim
@@ -3,4 +3,9 @@
 name="${1/.py/}"; shift
 
 pyfile="$(find ~/Sync/bin -name "${name}".py)"
+if [[ -z "${pyfile}" ]]; then
+    1>&2 printf "[ERROR] Could not find python script:  '${name}.py'\n"
+    exit 1
+fi
+
 tmux send-keys "clear && pushd ~/Sync/bin &> /dev/null && vim ${pyfile} ~/Sync/bin/tests/test_${name}.py && popd &> /dev/null && clear" "Enter"
diff --git a/vim/rim b/vim/rim
--- a/vim/rim
+++ b/vim/rim
@@ -7,7 +7,7 @@ else
 fi
 
 if [[ -z "${fpath}" ]]; then
-    echo "[ERROR] No filename matched."
+    1>&2 printf "[ERROR] No filename matched.\n"
     exit 1
 fi
 
